# Generated by Django 5.0.6 on 2024-05-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_car_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='max_power',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='top_speed',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
