# Generated by Django 5.0.6 on 2024-05-22 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_car_max_power_car_top_speed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='rental_end_date',
            new_name='rental_date',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='rental_start_date',
            new_name='return_date',
        ),
    ]
