# Generated by Django 5.0.6 on 2024-05-22 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_rename_rental_end_date_transaction_rental_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='rental_price',
        ),
    ]
