# Generated by Django 5.0.6 on 2024-05-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_remove_transaction_rental_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='rental_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
