# Generated by Django 5.0.6 on 2024-05-24 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_transaction_rental_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='rental_status',
        ),
    ]
